app/main/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('questions.urls', namespace='questions'))
]

app/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logout.html')
    )
]

app/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username',)

app/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/signup.html'

app/templates/users/login.html
{% extends "base.html" %}
{% load user_filters %}
{% block card_header %}Вход в систему{% endblock card_header %}
{% block form %}

  {% include 'includes/out_error_fields.html' %}

  {% if next %}
    <div class="alert alert-info" role="alert">
      Вы обратились к странице, доступ к которой возможен
      только для залогиненных пользователей.<br>
      Пожалуйста, авторизуйтесь.
    </div>
  {% else %}
    <div class="alert alert-info" role="alert">
      Пожалуйста, авторизуйтесь.
    </div>
  {% endif %}

  <form method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
    
    {% include 'includes/out_fields.html' with submit='Войти' %}

  </form>

{% endblock form %}

app/templates/users/logout.html
{% extends "base.html" %}
{% block header %} Вы вышли из системы {% endblock header %}
{% block form %} Вы вышли из своей учётной записи. {% endblock form %}

app/templates/users/signup.html
{% extends "base.html" %}
{% load user_filters %}
{% block card_header %}Регистрация{% endblock card_header %}
{% block form %}

  {% include 'includes/out_error_fields.html' %}

  <form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}

    {% include 'includes/out_fields.html' with submit='Зарегистрироваться' %}
  </form>

{% endblock form %}