app/main/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('questions.urls', namespace='questions'))
]

app/questions/urls.py
from django.urls import path

from . import views

app_name = 'questions'

urlpatterns = [
    path('', views.index, name='index'),
    path('rating/', views.all_results, name='rating'),
    path('my_results/', views.my_results, name='my_results'),
    path('questions/', views.get_question, name='questions'),
    path('finish_test', views.to_finish_test, name='finish_test'),
]

app/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logout.html')
    )
]

app/templates/includes/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <p class="m-0 text-dark text-center ">
    </p>
  <p class="m-0 text-dark text-center ">
  Проверь своего питона! © {{ year }}, все права защищены.
  </p>
</footer>

app/templates/includes/menu.html
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link text-dark" href="{% url 'questions:rating' %}">Рейтинг</a>
  </li>
  {% if user.is_authenticated %}
  <li class="nav-item">
    <a class="nav-link text-dark" href="{% url 'questions:my_results' %}">История Ваших тестов</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-dark" href="{% url 'questions:finish_test' %}">Завершить досрочно</a>
  </li>
  {% endif %}
</ul>

app/templates/includes/nav.html
<nav class="navbar navbar-light" style="background-color: #32CD32">
  <a class="navbar-brand" href="/">На главную страницу</a>
  <nav class="my-2 my-md-0 mr-md-3">
    {% if user.is_authenticated %}
      Пользователь: {{ user.username }}
      <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
    {% else %}
      <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
      <a class="p-2 text-dark" href="{% url 'users:signup' %}">Регистрация</a>
    {% endif %}
  </nav>
</nav> 

app/templates/includes/out_error_fields.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger" role="alert">
        {{ field.label }}: {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

app/templates/includes/out_fields.html
{% load user_filters %}
{% for field in form %}
  <div class="form-group row" aria-required={{ field.field.required }}>
    <label
      for="{{ field.id_for_label }}"
      class="col-md-4 col-form-label text-md-right">
      {{ field.label }}
      {% if field.field.required %}
        <span class="required">*</span>
      {% endif %}
    </label>
    <div class="col-md-6">
      {{ field|addclass:"form-control" }}
      {% if field.help_text %}
        <small
          id="{{ field.id_for_label }}-help"
          class="form-text text-muted">
          {{ field.help_text|safe }}
        </small>
      {% endif %}
    </div>
  </div>
  <br>
{% endfor %}
<div class="col-md-6 offset-md-4">
  <button type="submit" class="btn btn-primary">
    {% block button %}{{submit}}{% endblock %}
  </button>
</div>

app/templates/includes/paginator.html
{% if page.has_other_pages %}
  <nav>
    <ul class="pagination">
      {% if page.has_previous %}
        <li class="page-item">
          <a
            class="page-link"
            href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">&laquo; Предыдущая</span>
        </li>
      {% endif %}
      {% for i in page.paginator.page_range %}
        {% if page.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}
              <span class="sr-only">(текущая)</span>
            </span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page.has_next %}
        <li class="page-item">
          <a
            class="page-link"
            href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Следующая &raquo;</span>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}