app/main/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('questions.urls', namespace='questions'))
]

app/questions/urls.py
from django.urls import path

from . import views

app_name = 'questions'

urlpatterns = [
    path('', views.index, name='index'),
    path('rating/', views.all_results, name='rating'),
    path('my_results/', views.my_results, name='my_results'),
    path('questions/', views.get_question, name='questions'),
    path('finish_test', views.to_finish_test, name='finish_test'),
]

app/templates/base.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="viewport" content="width=980px, initial-scale=10.0">
    <title>{% block title %}Титле{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>

  <body>
    <div style= 'background-image: linear-gradient(to top, #32CD32 0%, #008000 100%);'>
      {% include 'includes/nav.html' %}
      <main>
        <div class="container">
          {% block header %}{% endblock header %}
          {% load user_filters %}
          {% block content %}
            <div class="row justify-content-center">
              <div class="col-md-8 p-5">
                {% include 'includes/menu.html' %}
                <div class="card">
                  <div class="card-header" style="display: flex; justify-content: center">
                    {% block card_header %}{% endblock card_header %}
                  </div>
                    <div class="card-body">
                    {% block form %}
                    {% endblock form %}
                    </div> <!-- card body -->
                  </div> <!-- card -->
                </div> <!-- col -->
            </div> <!-- row -->
          {% endblock content %}
        </div>
      </main>
      {% include 'includes/footer.html' %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/index.html
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock %}
{% block header %}{{ header }}{% endblock %}
{% block card_header %}{{ text }}{% endblock card_header %}
{% block form %}
  <h5 style="display: flex; justify-content: center">Доступный максимум баллов: {{ maximum }}</h5>
  <h6 style="display: flex; justify-content: center">{{ greeting|linebreaks }}</h6>
  <br>
  <h4 style="display: flex; justify-content: center" >
    <a class="p-2 text-dark" href="{% url 'questions:questions' %}">Впердё</a>
  </h4>
{% endblock form %}